### ISSUE TITLE
main.py not working

### ISSUE THREAD

**Issue by Tulasinathreddy** [N74NK/ZEC#1]
When I type 
python main.py +917330xxxxxx
then this comes:--
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    01\x08\x02\x0c\x02\x0c\x05\x08\x04\x0e\x0c\x08\x04\x08\x06\x08\x07\x08I\x10\x01\x10\x01'))
ValueError: bad marshal data (unknown type code)
PLEASE HELP

**Comment by N74NK** [comment]
Please reinstall your python or upgrade your python
